name: Sync fork

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch: {}

permissions: {}

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Merge upstream commits into master
        env:
          GH_TOKEN: ${{ secrets.FORK_UPDATE_TOKEN }}
        run: gh api -X POST "repos/${{ github.repository }}/merge-upstream" -f branch=master
